import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/frame370">Frame370</Link>
        </li>
        <li>
          <Link to="/paymentportalone">PaymentPortalOne</Link>
        </li>
        <li>
          <Link to="/paymentportalsix">PaymentPortalSix</Link>
        </li>
        <li>
          <Link to="/paymentportaleight">PaymentPortalEight</Link>
        </li>
        <li>
          <Link to="/paymentportaltwo">PaymentPortalTwo</Link>
        </li>
        <li>
          <Link to="/paymentportalfour">PaymentPortalFour</Link>
        </li>
        <li>
          <Link to="/paymentportalseven">PaymentPortalSeven</Link>
        </li>
        <li>
          <Link to="/paymentportalthree">PaymentPortalThree</Link>
        </li>
        <li>
          <Link to="/paymentportalone1">PaymentPortalOne1</Link>
        </li>
        <li>
          <Link to="/paymentportal">PaymentPortal</Link>
        </li>
        <li>
          <Link to="/paymentportalfive">PaymentPortalFive</Link>
        </li>
        <li>
          <Link to="/under60one">Under60One</Link>
        </li>
        <li>
          <Link to="/under60two">Under60Two</Link>
        </li>
        <li>
          <Link to="/above">Above</Link>
        </li>
        <li>
          <Link to="/under60three">Under60Three</Link>
        </li>
        <li>
          <Link to="/under60four">Under60Four</Link>
        </li>
        <li>
          <Link to="/under60five">Under60Five</Link>
        </li>
        <li>
          <Link to="/under60six">Under60Six</Link>
        </li>
        <li>
          <Link to="/abovethree">AboveThree</Link>
        </li>
        <li>
          <Link to="/abovefour">AboveFour</Link>
        </li>
        <li>
          <Link to="/under60seven">Under60Seven</Link>
        </li>
        <li>
          <Link to="/abovesix">AboveSix</Link>
        </li>
        <li>
          <Link to="/abovenine">AboveNine</Link>
        </li>
        <li>
          <Link to="/under60eight">Under60Eight</Link>
        </li>
        <li>
          <Link to="/under60">Under60</Link>
        </li>
        <li>
          <Link to="/sunkwaplan">Sunkwaplan</Link>
        </li>
        <li>
          <Link to="/login">Login</Link>
        </li>
        <li>
          <Link to="/aboveone">AboveOne</Link>
        </li>
        <li>
          <Link to="/abovetwo">AboveTwo</Link>
        </li>
        <li>
          <Link to="/abovefive">AboveFive</Link>
        </li>
        <li>
          <Link to="/aboveseven">AboveSeven</Link>
        </li>
        <li>
          <Link to="/aboveeight">AboveEight</Link>
        </li>
        <li>
          <Link to="/register">Register</Link>
        </li>
        <li>
          <Link to="/benefits60aboveenhanced">Benefits60aboveenhanced</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
